default: linux windows

watch:
  gow run .

buf:
  protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    ../shared/protobufs/api.proto -I ../shared

run:
  just -f {{justfile()}} buf
  go run .

linux:
  just -f {{justfile()}} buf
  go build -o target/linux .

windows:
  just -f {{justfile()}} buf
  GOOS=windows GOARCH=amd64 go build -o target/windows.exe .
